apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-api
  template:
    metadata:
      labels:
        app: time-api
    spec:
      containers:
      - name: time-api
        image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO}:${TAG}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: time-api-service
spec:
  selector:
    app: time-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer