name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: time-api-cluster
  GKE_ZONE: us-central1
  IMAGE: time-api
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_REPO: ${{ secrets.DOCKERHUB_REPO }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    #- name: Setup Google Cloud CLI
     # uses: google-github-actions/setup-gcloud@v0.2.0
     # with:
        #service_account_key: ${{ secrets.GCP_SA_KEY }}
        #project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$GITHUB_SHA api/

    - name: Push Docker image
      run: docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$GITHUB_SHA

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

    - name: Update Kubernetes deployment
      run: |
        kubectl set image deployment/time-api time-api=$DOCKERHUB_USERNAME/$DOCKERHUB_REPO:$GITHUB_SHA -n time-api
        kubectl rollout status deployment/time-api -n time-api

    - name: Test API
      run: |
        EXTERNAL_IP=$(kubectl get service time-api-service -n time-api -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        response=$(curl -s -o /dev/null -w "%{http_code}" http://$EXTERNAL_IP)
        if [ $response = "200" ]; then
          echo "API is accessible"
        else
          echo "API is not accessible"
          exit 1
        fi