name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: time-api-cluster
  GKE_ZONE: us-central1
  IMAGE: time-api

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Authenticate to Google Cloud
      run: echo "${{ secrets.GCP_SA_KEY }}" | gcloud auth activate-service-account --key-file=-

    - name: Extract service account email
      id: extract-sa-email
      run: echo "terraform_service_account=$(jq -r '.client_email' <<< '${{ secrets.GCP_SA_KEY }}')" >> $GITHUB_ENV

    - name: Enable Artifact Registry API
      run: gcloud services enable artifactregistry.googleapis.com

    - name: Grant Artifact Registry Writer role
      run: |
        SA_EMAIL=$(jq -r '.client_email' <<< '${{ secrets.GCP_SA_KEY }}')
        gcloud projects add-iam-policy-binding ${{ secrets.GCP_PROJECT_ID }} \
          --member="serviceAccount:${SA_EMAIL}" \
          --role="roles/artifactregistry.writer"

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA api/

    - name: Push Docker image
      run: docker push gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -var="project_id=$PROJECT_ID" -var="terraform_service_account=${{ env.terraform_service_account }}"
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="project_id=$PROJECT_ID" -var="terraform_service_account=${{ env.terraform_service_account }}"
      working-directory: ./terraform

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE

    - name: Update Kubernetes deployment
      run: |
        kubectl set image deployment/time-api time-api=gcr.io/$PROJECT_ID/$IMAGE:$GITHUB_SHA -n time-api
        kubectl rollout status deployment/time-api -n time-api

    - name: Test API
      run: |
        EXTERNAL_IP=$(kubectl get service time-api-service -n time-api -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
        response=$(curl -s -o /dev/null -w "%{http_code}" http://$EXTERNAL_IP)
        if [ $response = "200" ]; then
          echo "API is accessible"
        else
          echo "API is not accessible"
          exit 1
        fi